os: unstable
cache:
  - node_modules
environment:
  matrix:
    - nodejs_version: 6
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
build: off
matrix:
  fast_finish: true
artifacts:
  - path: SyncryptDesktop.zip
    name: SyncryptDesktop
test_script:
  - npm run package
  - 7z a SyncryptDesktop.zip release\*
version: '{build}'
shallow_clone: true
clone_depth: 1
deploy:
  tag: v0.3.2
  release: SyncryptDesktop-v0.3.2
  description: 'Windows Build'
  provider: GitHub
  auth_token:
    secure: cm6YGcbZ4btLnz/4ZdN9FsqObCDSK3QC9i5XIP2TmUcWVQ45sKjDSdBLGMgb0XVm
  artifact: /SyncryptDesktop.zip/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

